use_frameworks!

target 'PINFuture_Example' do
  pod 'PINFuture', :path => '../'

  target 'PINFuture_Tests' do
    inherit! :search_paths

    pod 'PINFuture', :path => '../'
    pod 'Specta'
  pod 'Expecta'
  end
end
